# Generated by Django 4.0.3 on 2022-03-13 17:09

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', profiles.models.UserManager()),
            ],
        ),
    ]
