# Generated by Django 4.2.30 on 2026-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_follow_unique_and_self_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ftp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='FTP'),
        ),
    ]
