# Generated by Django 4.2.30 on 2026-10-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_max_hr_and_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_follow_requests', to=settings.AUTH_USER_MODEL, verbose_name='кто запросил')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_follow_requests', to=settings.AUTH_USER_MODEL, verbose_name='кому запрос')),
            ],
            options={
                'verbose_name': 'запрос на подписку',
                'verbose_name_plural': 'запросы на подписку',
            },
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='profiles_followrequest_from_to_uniq'),
        ),
    ]
