# Generated by Django 4.0.3 on 2022-03-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_activity_track_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название изображения')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание изображения')),
                ('image', models.ImageField(upload_to='pictures', verbose_name='файл изображения')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='activities.activity', verbose_name='тренировка')),
            ],
            options={
                'verbose_name': 'пользовательское изображение',
                'verbose_name_plural': 'пользовательские изображения',
            },
        ),
    ]
