# Generated by Django 4.0.3 on 2022-03-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymedia',
            options={'verbose_name': 'фото с тренировки', 'verbose_name_plural': 'фото с тренировки'},
        ),
    ]
