# Generated by Django 4.0.3 on 2022-03-13 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Тренировка', max_length=255, verbose_name='название тренировки')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='продолжительность')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='дистанция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('started_at', models.DateTimeField(verbose_name='время начала тренировки')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitytype', verbose_name='тип тренировки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='спортсмен')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
            },
        ),
    ]
