# Generated by Django 4.0.3 on 2022-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='описание тренировки'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='название тренировки'),
        ),
    ]
