# Generated by Django 4.0.3 on 2022-03-16 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_description_alter_activity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='средняя скорость'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_active',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='время в движении'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='максимальная скорость'),
        ),
    ]
