# Generated by Django 4.2.30 on 2026-10-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_avg_speed_activity_duration_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_hr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='средний пульс'),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='средняя мощность'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_gain',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='набор высоты'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_hr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальный пульс'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальная мощность'),
        ),
        migrations.AddField(
            model_name='activity',
            name='streams',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='потоки данных'),
        ),
        migrations.AddField(
            model_name='activity',
            name='track_points',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='точки трека'),
        ),
    ]
