# Generated by Django 4.2.30 on 2026-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_metrics_and_track_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='внешний ID'),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_source',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='внешний источник'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('profile', 'external_source', 'external_id'), name='unique_activity_external_id'),
        ),
    ]
