# Generated by Django 4.2.30 on 2026-10-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_external_id_activity_external_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-started_at'], 'verbose_name': 'тренировка', 'verbose_name_plural': 'тренировки'},
        ),
    ]
