# Generated by Django 4.2.30 on 2026-10-05 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0008_activity_order_by_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Лайк'), ('🔥', 'Огонёк'), ('👏', 'Аплодисменты'), ('🍆', 'Баклажан'), ('🍌', 'Банан'), ('❤️', 'Сердечко')], max_length=8, verbose_name='эмодзи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='activities.activity', verbose_name='тренировка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reactions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
            },
        ),
        migrations.AddConstraint(
            model_name='activityreaction',
            constraint=models.UniqueConstraint(fields=('activity', 'profile'), name='unique_activity_reaction_per_profile'),
        ),
    ]
