# Generated by Django 4.2.30 on 2026-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avg_cadence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='средняя частота вращения'),
        ),
        migrations.AddField(
            model_name='activity',
            name='avg_moving_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='средняя скорость в движении'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_loss',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='спуск'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='максимальная высота'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='минимальная высота'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_cadence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальная частота вращения'),
        ),
        migrations.AddField(
            model_name='activity',
            name='normalized_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='нормализованная мощность'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tss',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='TSS'),
        ),
    ]
