# Generated by Django 4.2.30 on 2026-10-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0013_activity_map_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', max_length=3000, verbose_name='описание')),
                ('visibility', models.CharField(choices=[('private', 'Только я'), ('followers', 'Подписчики'), ('public', 'Все')], default='private', max_length=16, verbose_name='видимость')),
                ('track_points', models.JSONField(blank=True, default=list, verbose_name='точки маршрута')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='дистанция (км)')),
                ('elevation_gain', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='набор высоты')),
                ('elevation_loss', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='спуск')),
                ('map_preview', models.ImageField(blank=True, null=True, upload_to='route_maps', verbose_name='превью карты')),
                ('source_gpx', models.FileField(blank=True, null=True, upload_to='routes', verbose_name='исходный GPX')),
                ('surface_segments', models.JSONField(blank=True, default=list, verbose_name='сегменты покрытия')),
                ('surface_status', models.CharField(choices=[('pending', 'Ожидает'), ('ready', 'Готово'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='статус покрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('source_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_routes', to='activities.activity', verbose_name='исходная тренировка')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
                'ordering': ['-created_at'],
            },
        ),
    ]
