# Generated by Django 4.2.30 on 2026-10-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API-ключ')),
                ('athlete_id', models.CharField(blank=True, max_length=64, verbose_name='ID атлета')),
                ('is_active', models.BooleanField(default=False, verbose_name='активно')),
                ('initial_sync_done', models.BooleanField(default=False, verbose_name='начальная синхронизация выполнена')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя синхронизация')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervals_connection', to=settings.AUTH_USER_MODEL, verbose_name='спортсмен')),
            ],
            options={
                'verbose_name': 'подключение Intervals.icu',
                'verbose_name_plural': 'подключения Intervals.icu',
            },
        ),
    ]
